name: conda-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - jupyterlab
    - notebook
    - voila
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - altair
    - altair_viewer
